---
# This playbook deploys the whole application stack in this site.


- name: create
  ecs_ecr:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    security_token: "{{ token }}"
    name: "{{ item.name }}"
    state: "present"
  with_items: "{{ project.ecr_imgs }}"


  #TODO: migration of images between accounts