---
# This playbook deploys the whole application stack in this site.
- name: File [LAMBDAUPDATE] FILE EFS UPDATE lambda  state VALIDATE
  lambda_update:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    security_token: "{{ token }}"
    region: "{{project.region | default(null)}}"
    function_name: "{{ item.lambda }}"
    file_config: "{{ item.file_config }}"
  with_items: "{{ project.lambda_updates }}"
  when: (item.file_config is defined)

- name: Docker [LAMBDAUPDATE] DOCKER IMG UPDATE lambda  state VALIDATE 
  lambda_update:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    security_token: "{{ token }}"
    region: "{{project.region | default(null)}}"
    function_name: "{{ item.lambda }}"
    image_config: "{{ item.image_config }}"
  with_items: "{{ project.lambda_updates }}"
  when: (item.image_config is defined)

- name: Layer [LAMBDAUPDATE] LAYER UPDATE lambda  state VALIDATE
  lambda_update:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    security_token: "{{ token }}"
    region: "{{project.region | default(null)}}"
    function_name: "{{ item.lambda }}"
    layers: "{{ item.layers }}"
  with_items: "{{ project.lambda_updates }}"
  when: (item.layers is defined)